### ISSUE TITLE
Error with decapitated::download_chromium(): invalid 'path' argument

### ISSUE THREAD

**Issue by eoppe1022** [hrbrmstr/decapitated#5]
Whenever I run `decapitated::download_chromium()`, I get this error:

```
> decapitated::download_chromium()
Error in path.expand(path) : invalid 'path' argument
```

Any idea why?

**Comment by hrbrmstr** [comment]
Finally got to this. 

`path` needs to be specified but I defaulted it to `NULL` thinking I'd eventually auto-create a directory for it. I may put this on CRAN and adding that functionality is a pain due to CRAN's draconian policies so I have — for the moment — removed the `NULL` default.

TLDR: you need to specify a directory where it will install to.
